### ISSUE TITLE
Conflict with User Switching plugin

### ISSUE THREAD

**Issue by sisaacrussell** [BrianHenryIE/bh-wp-autologin-urls#24]
## Bug Report

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [X] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

Testing this plugin on a site with the [User Switching](https://wordpress.org/plugins/user-switching/) plugin installed throws the following error when visiting a link with the autologin enabled:

```
2024/02/18 06:14:04 [error] 39262#39262: *32635 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Undefined constant "USER_SWITCHING_SECURE_COOKIE" in /www/public/wp-content/plugins/user-switching/user-switching.php:1356
Stack trace:
#0 /www/public/wp-content/plugins/user-switching/user-switching.php(1291): user_switching_get_auth_cookie()
#1 /www/public/wp-includes/class-wp-hook.php(326): user_switching_clear_olduser_cookie('testclient@spru...')
#2 /www/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /www/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /www/public/wp-content/plugins/bh-wp-autologin-urls/src/wp-includes/class-login.php(166): do_action('wp_login', 'testclient@spru...', Object(WP_User))
#5 /www/public/wp-includes/class-wp-hook.php(324): BrianHenryIE\WP_Autologin_URLs\WP_Includes\Login->process(155)
....
```

Refreshing the page once after receiving the error will then load the page with the user logged in. Auto-login works as expected without the User Switching plugin active.

**Comment by BrianHenryIE** [comment]
I haven't looked into this properly yet, but I could not reproduce it with:

```
wp plugin install user-switching --activate 
wp autologin-urls get-url 3
Success: http://localhost:8080/bh-wp-autologin-urls/?autologin=3~5zvco5ujlHL0
```

... when I visited that URL it worked as expected.

I'll take a deeper look soon (I haven't actually looked into those functions named in that stacktrace yet).

**Comment by BrianHenryIE** [comment]
I think the correct fix for this is in the [johnbillion/user-switching](https://github.com/johnbillion/user-switching/) repo.

The login in this plugin occurs on the `determine_current_user` action and fires the `wp_login` action.

The user-switching plugin listens for `wp-login`, [user-switching.php#L1292-L1299](https://github.com/johnbillion/user-switching/blob/90a748b1e052c95874148580dac576cad4d8443d/user-switching.php#L1292-L1299), and checks for its cookie, 



 action which runs before `plugins_loaded`.

The `USER_SWITCHING_SECURE_COOKIE` constant is defined in a function that is hooked to `plugins_loaded`: [user-switching.php#L93-L113](https://github.com/johnbillion/user-switching/blob/90a748b1e052c95874148580dac576cad4d8443d/user-switching.php#L93-L113)

**Comment by BrianHenryIE** [comment]
Some discussion/progress on this issue: https://github.com/johnbillion/user-switching/issues/115
